# Generated by Django 4.0.1 on 2022-02-21 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('pytho', 'python'), ('c', 'c'), ('c++', 'c++'), ('java', 'java'), ('data structure', 'data structure'), ('javascript', 'javascript')], default='c', max_length=20),
            preserve_default=False,
        ),
    ]
