# Generated by Django 4.0.1 on 2022-02-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0003_alter_question_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='user',
            field=models.CharField(default='aditya', max_length=70),
            preserve_default=False,
        ),
    ]
