# Generated by Django 4.0.1 on 2022-02-23 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('online', '0004_question_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('institute', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=30)),
                ('branch', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='images')),
                ('points', models.IntegerField()),
                ('solved', models.IntegerField()),
                ('correct', models.IntegerField()),
                ('worng', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
